[project]
name = "unstake-estimate"
authors = ["Stacks Developer"]
description = "Advanced unstaking and liquidity estimation toolkit"
telemetry = false
requirements = []
[contracts.unstake-core]
path = "contracts/unstake-core.clar"
depends_on = []

[contracts.liquidity-estimator]
path = "contracts/liquidity-estimator.clar"
depends_on = []

[contracts.reward-calculator]
path = "contracts/reward-calculator.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
